# Generated by Django 3.0.8 on 2020-08-06 04:42

from django.db import migrations, models
import patientInformation.models


class Migration(migrations.Migration):

    dependencies = [
        ('patientInformation', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientinformation',
            name='image1',
            field=models.ImageField(blank=True, null=True, upload_to=patientInformation.models.upload_location),
        ),
        migrations.AddField(
            model_name='patientinformation',
            name='image2',
            field=models.ImageField(blank=True, null=True, upload_to=patientInformation.models.upload_location),
        ),
        migrations.AddField(
            model_name='patientinformation',
            name='image3',
            field=models.ImageField(blank=True, null=True, upload_to=patientInformation.models.upload_location),
        ),
        migrations.AlterField(
            model_name='patientinformation',
            name='patientRecordNumber',
            field=models.SlugField(max_length=11, null=True, unique=True),
        ),
    ]
