# Generated by Django 3.0.8 on 2020-08-06 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patientInformation', '0003_patientinformation_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientinformation',
            name='patientSex',
            field=models.CharField(choices=[('Female', 'Female'), ('Male', 'Male')], default='male', max_length=6),
        ),
    ]
