# Generated by Django 3.1 on 2020-08-15 05:16

from django.db import migrations, models
import patientInformation.models


class Migration(migrations.Migration):

    dependencies = [
        ('patientInformation', '0008_auto_20200806_2128'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patientinformation',
            old_name='image1',
            new_name='patient_image',
        ),
        migrations.RemoveField(
            model_name='patientinformation',
            name='image2',
        ),
        migrations.RemoveField(
            model_name='patientinformation',
            name='image3',
        ),
        migrations.AddField(
            model_name='patientinformation',
            name='injury_image',
            field=models.ImageField(blank=True, null=True, upload_to=patientInformation.models.upload_location),
        ),
    ]
